### ISSUE TITLE
Unexplainable non-identifiability before the changepoint (reproducible code)

### ISSUE THREAD

**Issue by regicid** [lindeloev/mcp#162]
Hello and a huge thanks for this amazing package!

I'm trying to fit a two-segments regression line. The data feature a pretty clear breakpoint. All looks fine in the estimation, but the convergence is clearly not reached for `int_1` and `date_1` (Rhat=11, messy plot_par).

The problem seems to come from non-identifiability. I attach the hexagon plot of the two non-converging parameters: it's a clear straight line y=x. Which does not really makes sense to me: there is no correlation between date and my IV before the changepoint (.03).

One last thing that I can't understand: when I plot the fit, it looks pretty fine, all grey lines are basically the same. It seems to me that since the fit does not converge, I should have much more variability in the shape of the fit there, right? So, I'm wondering if it's not the diagnostic functions (summary & plot_pars) that have a bug here, even though everything's fine?

Reproducible code here:

```
df = read.csv("https://shiny.ens-paris-saclay.fr/guni/query?corpus=la_presse&mot=pas&from=1851&to=1852")
df$date = as.Date(paste(df$annee,df$mois,df$jour,sep="-"))
df$week <- strftime(df$date, format = "%V")
df = df %>% group_by(annee,week) %>% summarise(n = sum(n),total=sum(total),date = mean(date))
df$ratio = df$n/df$total

df$date = as.numeric(df$date)
fit = mcp(model,data = df,sample="both",par_x = "date")
summary(fit)
plot(fit, q_predict = TRUE)
plot_pars(fit, type = "dens_overlay",prior=T)
plot_pars(fit, pars = c("int_2", "date_2"), type = "hex"))

```
And the figures:
![image](https://github.com/lindeloev/mcp/assets/57593826/b540104a-8737-4e71-a93b-2621ba636fdd)
![image](https://github.com/lindeloev/mcp/assets/57593826/a950545c-8679-4af0-9e90-2d222934ee77)
![image](https://github.com/lindeloev/mcp/assets/57593826/d0d010c2-43cb-4e01-b33a-44f137948d9e)

**Comment by lindeloev** [comment]
Thanks for the code!

Interesting case. It's clear that it can get very narrow and "correct" posteriors for all parameters. But it seems to converge overly slow on the intercept and slope in first segment where they trade off perfectly within a very very narrow range in the first segment. That's why it isn't visible on `plot(fit)`.

I tried scaling the variables (`date = date / 100000; ratio = ratio * 1000`) to be more suitable for the priors, but that didn't improve it.

Two solutions:

1. Remove the intercept from the first segment, if your theory allows it. `ratio ~ 0 + date`. Gives Rhat = 1 here.
2. Try defining priors that are more aligned with the scale of the parameters you are interested in here and see if that helps.
3. Increase `mcp(..., iter = 10^5)`, perhaps even increasing the number of `chains` too. Gives Rhat = 1 here.

I used this model

```r
model = list(
  ratio ~ 1 + date,
  ~ 1 + date
)
```

I think the default `plot_pars(fit)` is much more informative here than just plotting the density of the prior:
![image](https://github.com/lindeloev/mcp/assets/1439417/9d6390e3-4d68-4b39-a14d-0ca8aa937071)


Without the intercept in the first segment, I get:
![image](https://github.com/lindeloev/mcp/assets/1439417/ab660e40-ff80-45b9-bbe3-eadcab3c8740)

BTW, no need to set `par_x = "date"`. `par_x` is only used for intercept-only models.
