### ISSUE TITLE
Is there a "predict" function?

### ISSUE THREAD

**Issue by jpzhangvincent** [lindeloev/mcp#78]
It seems there isn't a "predict" function. Please correct me if I'm wrong?

I think the predicted values would be generated from the model parameters in the last segment, correct?

**Comment by lindeloev** [comment]
@jpzhangvincent, yes, I hope to include a `predict` function in an upcoming release within a few months. It is already semi-implemented in `plot(fit, q_predict = TRUE)` but I need to figure out how (or whether) to do out-of-sample predictions for AR(N) models.

**Comment by jpzhangvincent** [comment]
Just curious, when will be the next release? I had implemented a rough version of the "predict" function for my project. I'd love to see whether I can use the new version if you had implemented it. Thanks.

**Comment by lindeloev** [comment]
I think `mcp` 3.0 will be on CRAN about one month from now. I have a version working locally, but need to think more about the API and to include support for varying effects and `AR(N)` models, The latter in particular requires some work.

I might post work-in-progress here to get your opinion on the output format and the API :-)

**Comment by lindeloev** [comment]
I implemented `predict()` in the development version. Could you take it for a spin and let me know what you think?

    install_github("lindeloev/mcp")

You can read the function doc (`?predict.mcpfit`) for more info. I would be really happy to receive feedback/suggestions on the API and the docs. 

FYI, this release also comes with several related functions: `fitted()`, `residuals()` and `pp_check()`. They should "feel" similar to `predict`.

**Comment by jpzhangvincent** [comment]
@lindeloev Awesome! Thanks for the update. I have played around a bit.  A couple of suggestions/questions I have so far are:

1. Do you think we can add an option to use fixed "seed" to control the randomness of sampling? I use this package for forecasting. I hope to get reproducible/same results.
2. In practice, we often have future change points for the forecasting problem. Right now, I have a solution by imposing the estimated impacts on top of the forecasts separately. But I'm wondering whether you have thoughts on how we can incorporate priors for future change points into the forecasting horizon in a Bayesian framework.

**Comment by lindeloev** [comment]
@jpzhangvincent 

1. Calling `set.seed(42)` before `predict` is deterministic here. I would prefer this "base R approach" to an extra argument. Does this work in your end?

2. That's a neat idea. I think this can be hacked (see below), but I'd like to hear your thoughts on a good API for supporting this more formally. And whether the following constitutes a solution to your forecasting problem. This approach in headlines 

   - Specify a model for the observed data.
   - Specify a model that includes the future region and the priors associated with the "new" parameters.
   - Sample this extended model. This will inform the "observed" parameters with prior + data and the "future" parameters" just using the prior.

Here's an example where two segments are observed (a slope-change), and then adding prior knowledge about a future intercept-change:

```r
# Model for known data
model_fit = list(
  y ~ 1 + x,
    ~ 0 + x
)

# Simulate some data, just for the present example
empty = mcp(model_fit, sample = FALSE)
df = data.frame(x = 1:100)
df$y = empty$simulate(df$x, cp_1 = 50, int_1 = 20, x_1 = 1, x_2 = -0.5, sigma_1 = 8)

# Model including unknown parameters
model_predict = c(
  model_fit,
  list(
    ~ 1   # The new segment(s)
  )
)

# Prior knowledge about the "new" parameters
prior = c(
  empty$prior,
  list(
    cp_2 = "dnorm(150, 10) T(MAXX, )",
    int_3 = "dunif(70, 80)"
  )
)

# Fit it
fit = mcp(model_predict, df, prior)


# Plot fits (could use predict() as well here)
xx = 1:200
pred = fitted(fit, data.frame(x = xx), summary = FALSE, nsamples = 50)
ggplot(pred, aes(x = x, y = fitted, group = .draw)) + 
  geom_line(alpha = 0.2)
```

![image](https://user-images.githubusercontent.com/1439417/88444182-24cc5b00-ce1c-11ea-8099-5db880e2cc2a.png)


In terms of an API for this, I can think of two improvements to the above:

1. You should plot this just using `plot(fit, newdata = data.frame(x = 1:200))`. `plot` currently only evaluates the function within the observed region.

2. Omit doing the "prior-transfer" by somehow "tagging" changepoint(s) as before/after the observed range (out of bounds, OOB). Since you would always want to specify a non-default prior for such change points, a practical solution would be to do it in the prior string itself:

```
prior = list(
  cp_1 = "OOB_LOWER dnorm(-30, 10)",
  cp_3 = "OOB_UPPER dnorm(150, 10)"
)
```

... and `mcp` will then, as usual, add the appropriate truncation to ensure ordering of the change points. Alternatively, there could be an argument `mcp(model, data, prior, oob_cp = c("cp_1", "cp_3"))`, but that would require the user to go two places.

As a reminder to self, predicting with "changepoints backwards in time" would need all other change point indices to increment or a way to specify negative change point indices, The former is easier to implement.

**Comment by lindeloev** [comment]
@jpzhangvincent I just updated the plot above with a better visualization, FYI.

**Comment by jpzhangvincent** [comment]
Oh wow, that's a nice trick. I like your first idea of specifying the prior string. I'd love to see the feature. It would allow for incorporating human knowledge about future events into the bayesian forecasting framework.

**Comment by jpzhangvincent** [comment]
Just another question for the `predict` function, I found the `predict` function is very slow when trying to apply for a longer horizon and gave me errors of "vector memory exhausted". 

To compare, I had implemented a rough and simpler version of `predict` function that takes much less time and able to handle longer horizon. But I'm not 100% sure about the correctness of my implementation. Can you review and provide your feedback?

`
# extract posterior samples for validation and inference
extract_post_samples <- function(bayes_pod_model) {
  regex_pars_pop <- paste0(bayes_pod_model$pars$population, collapse="|")
  mcmc_post_samples_ls <- bayes_pod_model$mcmc_post
  
  mcmc_post_samples_df <- mcmc_post_samples_ls %>%
    tidybayes::spread_draws(!!rlang::sym(regex_pars_pop), regex = TRUE) %>%  
    tidybayes::sample_draws(n = 1000) 
  return(mcmc_post_samples_df)
}

# forecast based on the selected bayes model
forecast_bayesreg_model<- function(bayes_model, forecast_h = 30) {
  raw_df <- bayes_model$data
  xvar = rlang::sym(bayes_model$pars$x)
  yvar = rlang::sym(bayes_model$pars$y)
  
  # generate posterior samples(of predicted values) from fitting the training data
  eval_at = mcp:::get_eval_at(bayes_model, NULL) 
  
  bayes_post_samples_df <- extract_post_samples(bayes_model)
  
  # generate posterior samples for forecasting 
  pred_ds <- last(raw_df$ds) + seq(0, length.out = forecast_h, by = 1) #depending on time granularity of time series

  fct_post_samples_df <- bayes_post_samples_df %>% 
    tidyr::expand_grid(!!xvar := pred_ds) %>%
    dplyr::mutate(predicted_ = rlang::exec(bayes_model$simulate, !!!., type = "predict", rate = TRUE, add_attr = FALSE))
  
  fct_quantiles_data = dplyr::mutate(fct_post_samples_df, y_quant = .data$predicted_) %>% 
    tidyr::expand_grid(quant = c(0.025, 0.5, 0.975)) %>%
    group_by(ds, quant) %>% 
    summarise(y = stats::quantile(.data$y_quant, probs = .data$quant[1])) %>% 
    ungroup()
  
  forecasts <- fct_quantiles_data %>% 
    pivot_wider(id_cols = "ds", names_from = "quant", names_prefix = "Q", values_from = "y") %>% 
    transmute(ds, yhat = Q0.5, yhat_lower = Q0.025, yhat_upper = Q0.975)
  return(forecasts)
}
`

**Comment by lindeloev** [comment]
Yeah, I think it's pretty awesome too! Wouldn't have thought of it if not for your question.

Just before testing this performance issue further myself, did the your script perform faster too if you set the same number of samples in `predict`? (`predict(..., nsamples = 1000)`).

**Comment by lindeloev** [comment]
I wrote up a page on `predict()` etc. and added a write-up of the "forecasting with future change points" example here: https://lindeloev.github.io/mcp/articles/predict.html.

I've also made many updates to the packages in the last few days, FYI.

**Comment by jpzhangvincent** [comment]
That's awesome! The documentation is really helpful! 

To your last question, I haven't specifically looked at the performance difference using difference 'nsamples'. I guess it would be faster if smaller 'nsamples' is chosen. Just curious, is there a rule of thumb to select 'nsamples' for generating (Bayesian) prediction intervals in terms of statistical soundness and sufficiency?

**Comment by lindeloev** [comment]
The general rule would have to be an acceptable number of effective samples
(see summary output). I don't think summary takes nsamples at the moment,
though, so you may need to find a function in tidybayes to do it.

Definitely above 100, but there's no hard decision rule. MCMC error
decreases with the number.
