### ISSUE TITLE
Bug when fitting relative slope in a formula form?

### ISSUE THREAD

**Issue by jpzhangvincent** [lindeloev/mcp#80]
I have a question regarding how to configure relative slope in a formula form.

I read the documentation and it seems we can use "rel" to fit the relative change. So I did the same for my time series use case as following. 
<img width="682" alt="Screen Shot 2020-06-15 at 12 54 56 PM" src="https://user-images.githubusercontent.com/7220686/84700220-a967b780-af07-11ea-877f-2c07b2a53d07.png">

But it gives me an upward slope which is supposed to show a downward trend based on our domain knowledge. So I inspect the "jags_code". It seems it's modeled as "(x_i-1 + x_i)" for the relative part. What I would like to fit is to model the relative change of the previous slope as a multiplier. 

Thanks to the "custom_jags" argument. I twisted a little bit of the "jags_code" by specifying a multiplier parameter "f_2" that follows a uniform distribution ([0.1 ~1]) and constructing the last slope as "x_2 = f_2*x_1" to replace the previous "(x_2+x_1)" component. That gives me a much better fit in the sense of being consistent with our prior knowledge.
<img width="676" alt="Screen Shot 2020-06-15 at 12 55 17 PM" src="https://user-images.githubusercontent.com/7220686/84700973-fa2be000-af08-11ea-964f-4a246d85e6fa.png">

I'm wondering whether this is a bug of fitting with a relative slope as I'm not sure why the additive formulation(x_i-1 + x_i)) can help extrapolate the relative change. Or do you have any other suggestions to specify in a formula form for my goal? (so I don't need to twist the jags code)

Thanks very much!

**Comment by lindeloev** [comment]
Relative slope merely means that the parameter is the *change* in slope *relative* to the prior segment. That's why it's additive. So if the slope is -1 in segment 2 and -0.5 in segment 2, the relative change would be (positive) 0.5. This is meant for setting priors in cases where you have knowledge about the relative change but not the absolute.

Do you think that a multiplicative change is common? Can I ask what your case is and what domain of problems similarly would benefit from a multiplicative formulation? It would need to be a common use case before I extend the API to support it. I guess you could do something like `y ~ 1 + rel(x, *)` to specify multiplication with `rel(x) == rel(x, +)` being the default.

Is it the case that you have prior knowledge that the slope in segment 2 should be negative? Then you can model an absolute slope for the second segment (the default) and set a prior that it's negative, e.g.,

```
model = list(
    y ~ 1 + x,
    ~ 1 + x
)
prior = list(x_2 = "dnorm(0, 5) T(, 0)")
fit = mcp(model, data, prior)
```

Great that you solved it in your case, in any way!

**Comment by jpzhangvincent** [comment]
Got it. Thanks for the response! Yes, I have prior knowledge that the slope in segment 2 should be negative because it's supposed to be a downward trended metric. I was just hoping to use the relative slope in terms of percentage change to construct the prior, which is more useful in the business setting for interpretation purposes.

**Comment by lindeloev** [comment]
@jpzhangvincent, I'm considering dropping support for `rel()` in mcp formulas, but only if it's rarely used. Did you end up using `rel()` or could you do without?
